export const fakedCars = [
    {
        immatriculation: 'AB-123-CD',
        brand: 'Toyota',
        model: 'Corolla',
        year: 2018,
        mileage: 30000,
        color: 'Red',
        fuel: 'Gasoline',
        price: 15000,
        power: 132,
        description: 'A reliable and fuel-efficient sedan.',
        transmission: 'Automatic',
        images: [
            'https://example.com/car1-img1.jpg',
            'https://example.com/car1-img2.jpg',
        ],
        status: 'available',
    },
    {
        immatriculation: 'EF-456-GH',
        brand: 'Honda',
        model: 'Civic',
        year: 2020,
        mileage: 15000,
        color: 'Blue',
        fuel: 'Gasoline',
        price: 20000,
        power: 158,
        description: 'A compact car with sporty handling.',
        transmission: 'Manual',
        images: [
            'https://example.com/car2-img1.jpg',
            'https://example.com/car2-img2.jpg',
        ],
        status: 'available',
    },
    {
        immatriculation: 'IJ-789-KL',
        brand: 'Ford',
        model: 'Focus',
        year: 2019,
        mileage: 25000,
        color: 'White',
        fuel: 'Diesel',
        price: 18000,
        power: 160,
        description: 'A versatile hatchback with modern features.',
        transmission: 'Automatic',
        images: [
            'https://example.com/car3-img1.jpg',
            'https://example.com/car3-img2.jpg',
        ],
        status: 'available',
    },
];
